"""Add test data

Revision ID: 74e77f4a6d9b
Revises: b2332ecaa39d
Create Date: 2025-02-12 17:42:19.611730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from app.src.app.db.models.building import BuildingModel
from app.src.app.db.models.organization import OrganizationModel
from app.src.app.db.models.phone_number import PhoneNumberModel
from app.src.app.db.models.activity import ActivityModel


# revision identifiers, used by Alembic.
revision = '74e77f4a6d9b'
down_revision = 'b2332ecaa39d'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    # Создание зданий
    building1 = BuildingModel(
        address="Москва, Новая, 13Б, этаж 3, офис 33",
        latitude=55.760236,
        longitude=37.612991
    )
    building2 = BuildingModel(
        address="Москва, Столешников переулок, 2с1",
        latitude=55.761852,
        longitude=37.612066
    )
    session.add_all([building1, building2])
    session.commit()

    # Создание организаций
    organization1 = OrganizationModel(
        name="ООО ВсегдаЕда",
        building_id=building1.id
    )
    organization2 = OrganizationModel(
        name="ИП Иванов",
        building_id=building2.id
    )
    session.add_all([organization1, organization2])
    session.commit()

    # Создание деятельностей
    food_category = ActivityModel(name="Еда", organization_id=organization1.id)
    session.add(food_category)
    session.commit()

    food_production = ActivityModel(name="Произодство готовой еды", parent_id=food_category.id, organization_id=organization1.id)
    food_sales = ActivityModel(name="Продажа еды", parent_id=food_category.id, organization_id=organization1.id)

    truck_category = ActivityModel(name="Машины Грузовые", organization_id=organization2.id)
    session.add(truck_category)
    session.commit()

    truck_repair = ActivityModel(name="Ремонт грузовых машин", parent_id=truck_category.id, organization_id=organization2.id)
    truck_parts = ActivityModel(name="Запчасти для грузовых машин", parent_id=truck_category.id, organization_id=organization2.id)
    tent_repair = ActivityModel(name="Ремонт тенов", parent_id=truck_category.id, organization_id=organization2.id)

    session.add_all([food_production, food_sales, truck_repair, truck_parts, tent_repair])
    session.commit()

    # Добавление номеров телефонов
    phone_numbers1 = [
        PhoneNumberModel(number="999-999-11-22", organization_id=organization1.id),
        PhoneNumberModel(number="888-777-11-22", organization_id=organization1.id),
        PhoneNumberModel(number="999-111-22-33", organization_id=organization1.id)
    ]
    phone_numbers2 = [
        PhoneNumberModel(number="909-909-22-33", organization_id=organization2.id),
        PhoneNumberModel(number="909-909-22-34", organization_id=organization2.id)
    ]
    session.add_all(phone_numbers1 + phone_numbers2)
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
